"""init tables

Revision ID: 4cf525d5891f
Revises: 
Create Date: 2025-12-14 08:29:11.135139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4cf525d5891f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adotante',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferencias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_adotante', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_adotante')
    )
    op.create_table('animal',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('data_resgate', sa.Date(), nullable=False),
    sa.Column('status_adocao', sa.Boolean(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_animal')
    )
    op.create_table('atendente',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_atendente', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_atendente')
    )
    op.create_table('adocao',
    sa.Column('data_adocao', sa.Date(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelamento', sa.Boolean(), nullable=False),
    sa.Column('id_adocao', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('id_adotante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adotante'], ['adotante.id_adotante'], ),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id_animal'], ),
    sa.PrimaryKeyConstraint('id_adocao')
    )
    op.create_table('adocaoatend',
    sa.Column('id_adocao', sa.Integer(), nullable=False),
    sa.Column('id_atendente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adocao'], ['adocao.id_adocao'], ),
    sa.ForeignKeyConstraint(['id_atendente'], ['atendente.id_atendente'], ),
    sa.PrimaryKeyConstraint('id_adocao', 'id_atendente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adocaoatend')
    op.drop_table('adocao')
    op.drop_table('atendente')
    op.drop_table('animal')
    op.drop_table('adotante')
    # ### end Alembic commands ###
